<?php
declare(strict_types=1);

// InvoiceExtraction SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

InvoiceExtractionUtility::setRegistrar(function (InvoiceExtractionUtility $u): void {
    $u->clean = [InvoiceExtractionClean::class, 'call'];
    $u->done = [InvoiceExtractionDone::class, 'call'];
    $u->make_error = [InvoiceExtractionMakeError::class, 'call'];
    $u->feature_add = [InvoiceExtractionFeatureAdd::class, 'call'];
    $u->feature_hook = [InvoiceExtractionFeatureHook::class, 'call'];
    $u->feature_init = [InvoiceExtractionFeatureInit::class, 'call'];
    $u->fetcher = [InvoiceExtractionFetcher::class, 'call'];
    $u->make_fetch_def = [InvoiceExtractionMakeFetchDef::class, 'call'];
    $u->make_context = [InvoiceExtractionMakeContext::class, 'call'];
    $u->make_options = [InvoiceExtractionMakeOptions::class, 'call'];
    $u->make_request = [InvoiceExtractionMakeRequest::class, 'call'];
    $u->make_response = [InvoiceExtractionMakeResponse::class, 'call'];
    $u->make_result = [InvoiceExtractionMakeResult::class, 'call'];
    $u->make_point = [InvoiceExtractionMakePoint::class, 'call'];
    $u->make_spec = [InvoiceExtractionMakeSpec::class, 'call'];
    $u->make_url = [InvoiceExtractionMakeUrl::class, 'call'];
    $u->param = [InvoiceExtractionParam::class, 'call'];
    $u->prepare_auth = [InvoiceExtractionPrepareAuth::class, 'call'];
    $u->prepare_body = [InvoiceExtractionPrepareBody::class, 'call'];
    $u->prepare_headers = [InvoiceExtractionPrepareHeaders::class, 'call'];
    $u->prepare_method = [InvoiceExtractionPrepareMethod::class, 'call'];
    $u->prepare_params = [InvoiceExtractionPrepareParams::class, 'call'];
    $u->prepare_path = [InvoiceExtractionPreparePath::class, 'call'];
    $u->prepare_query = [InvoiceExtractionPrepareQuery::class, 'call'];
    $u->graphql_body = [InvoiceExtractionGraphql::class, 'body'];
    $u->graphql_errors = [InvoiceExtractionGraphql::class, 'errors'];
    $u->result_basic = [InvoiceExtractionResultBasic::class, 'call'];
    $u->result_body = [InvoiceExtractionResultBody::class, 'call'];
    $u->result_headers = [InvoiceExtractionResultHeaders::class, 'call'];
    $u->transform_request = [InvoiceExtractionTransformRequest::class, 'call'];
    $u->transform_response = [InvoiceExtractionTransformResponse::class, 'call'];
});
